version: '3.8'
services:
  nginx:
    build:
      context: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - lambda

  lambda:
    build:
      context: ./Backend
    ports:
      - "9000:8080"