name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Sprawdzanie kodu repozytorium
    - name: Checkout code
      uses: actions/checkout@v3

    # Logowanie do GitHub Container Registry (opcjonalne, jeśli używasz prywatnego registry)
    # - name: Log in to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # Budowanie obrazu Dockera
    - name: Build Docker image
      run: docker build -t my-go-app .

    # Uruchamianie testów wewnątrz kontenera
    - name: Run tests in Docker
      run: docker run --rm my-go-app
